en:
  languageName: English
  weight: 1
  params:
    description: "Kamitani Lab – Neuroinformatics – Kyoto University & ATR"

ja:
  languageName: 日本語
  weight: 2
  title: 神谷研究室
  params:
    description: "神谷研究室 – 神経情報学 – 京都大学・ATR"
  menu:
    main:
      - name: 概要
        url: /about/
        weight: 10
      - name: メンバー
        url: /people/
        weight: 20
      - name: 研究
        url: /research/
        weight: 30
      - name: 論文
        url: /publication/
        weight: 35
      - name: アート
        url: /project/
        weight: 40
      - name: ニュース
        url: /post/
        weight: 50
      - name: リンク
        url: /links/
        weight: 80
      - name: 検索
        url: /search/
        weight: 90
